### ISSUE TITLE
Trouble running/installing. 

### ISSUE THREAD

**Issue by sealevelcain** [JLErvin/squash#2]
So somehow I've managed to mess this up even though the install instructions are like 3 items long. Figures. I'm running linux mint if that makes any difference. 

The problems begin on the third step/running the installation script. After entering ./install.sh I'm presented with the following message: cp: cannot stat '/home/xxxx/squash/test_themes/*': No such file or directory. 

Any ideas?

**Comment by JLErvin** [comment]
I have updated the installation instructions and removed in the install script. This new system should make it easier for them to adapt squash to their own system. 
The README now reads as follows:

> You will need to edit squash to point to your themes and desired colors directory. You can do this by changing the first couple lines in squash. They default to the following:

    THEMES_DIR=~/.config/squash/themes
    CACHE_DIR=~/.cache/squash
    OB_DIR=~/.local/share/themes/generic/openbox-3

After these have been set, you can change your other applications to point to these directories. Examples of these are provided in the Usage section.
