### ISSUE TITLE
I can not run it

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [JLErvin/squash#3]
![2018-06-03-003922_1024x600_scrot](https://user-images.githubusercontent.com/19531907/40881089-f432dba4-66c6-11e8-99bf-7596399bb7b0.png)

**Comment by JLErvin** [comment]
Try running `squash` using a different shell. The leading `sh` should not be necessary, as `squash` should run as a bash script. 

Does it work with the following command? :
```
squash designr
```

**Comment by xxxvik-xakerxxx** [comment]
no does not work, I did not transfer files to folders bin
this is not indicated in the instructions
![2018-06-03-083516_1024x600_scrot](https://user-images.githubusercontent.com/19531907/40883591-a62fdb76-6709-11e8-9260-1207ac0fb36d.png)

**Comment by JLErvin** [comment]
Try running with the new `install.sh` script and instructions and see if you get the same error.
